name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3]
        dependency-version: [stable]

    name: PHP${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath
          coverage: none
          tools: composer:v2

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-${{ runner.os }}-${{ matrix.php }}-${{ matrix.dependency-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php }}-${{ matrix.dependency-version }}-

      - name: Install dependencies (stable)
        if: matrix.dependency-version == 'stable'
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist --testdox
